FORMAT: 1A
HOST: https://api.stayapp.com.br

# StayApp

A API do StayApp disponibiliza uma forma de capturar os seus clientes, acessar informações dos seus cards e consultar segmentações personalizadas através de uma API no padrão REST.

## Endpoints

https://api.stayapp.com.br/

## Como obter token de acesso?

Para obter os tokens públicos e privados que irão autenticar a sua requisição nesta API, você deve logar com um usuário com permissões administrativas na empresa que deseja integrar e acessar a página de integrações pelo menu de gerência (engrenagem).

Após acessar a página de integração, clique no botão de gerar token da empresa a qual você deseja realizar a integração. É importante ressaltar que tokens privados são mostrados apenas uma única vez, então certifique-se de copia-lo no momento da sua criação, caso contrário será necessário gerar novos tokens.

Cuidado ao gerar novamente tokens já existentes. No momento da geração de novos tokens, os antigos criados por você na mesma empresa são automaticamente revogados, tornando necessária a substituição dos mesmos.

Os Tokens são objetos que ajudam a identificar um usuário em uma determinada empresa, logo, caso você faça uma integração e realize uma captura de cliente, o operador que irá constar nessa captura será o usuário que gerou o Token.

## Cards [/integration/tickets/]
Busca a lista de cards cadastrados pela empresa. Pode ser utilizado para buscar o ID dos cards no momento de realizar a integração de captura de clientes.

### Listar cards [GET]

+ request

    + Headers
    
            Token: <Token Privado StayApp>
            Content-type: application/x-www-form-urlencoded
     

+ Response 200 (application/json)
    
    
    + Body
    
            [
                "-Kv-QuesVKb5jH8SZ0lI": {
                    "description": "Descricao",
                    "franchise_id": "-L2L8rcJciDRLu5KcrR0",
                    "is_buy_value_enabled": false,
                    "is_canceled": true,
                    "is_cod_enabled": false,
                    "is_public": true,
                    "name": "Financeira",
                    "needs_approval": false,
                    "stamp_objective": 1000,
                    "stamp_type": "PERCENT",
                    "id": "-LPkc174nq9e-lk5O3qT"
                },
                "-Kv2Y43Py5E5q4Yi1nYJ": {
                    "company_id": "xyz",
                    "description": "A cada 10 pratos, 1 é por nossa conta.",
                    "image_path": "images/tickets/339ff8ba-a8f6-1ebe-e7c9-c11a6a4a1e16.jpeg",
                    "is_buy_value_enabled": true,
                    "is_canceled": false,
                    "is_cod_enabled": true,
                    "is_public": true,
                    "name": "10 pratos!",
                    "needs_approval": false,
                    "stamp_objective": 10,
                    "stamp_type": "COUNT",
                    "id": "-Kv2Y43Py5E5q4Yi1nYJ"
                }
            ]
    

+ Response 400 (application/json)

    + Body
    
            {
                "error": "token-invalid/token-not-found"
            }

## Captura de clientes [/integration/addStamp]
Capturar (fidelizar) clientes na sua empresa.

### Registrar uma captura [POST]

+ Attributes

    + number (string, required) - Número celular do cliente a ser fidelizado (DDI + DDD + numero).
    
        Exemplos válidos: +5562987776255, 556282998173
    
    + amount (number, required) - Valor da fidelização
    
        Caso o card não seja de valor de compra, o mesmo não permite que a fidelização ocorra com números quebrados,
        fazendo com que o mesmo seja arredondado para baixo.
    
    + ticket_id (string, required) - Identificador do card
    
        Pode ser obtido através do endpoint "/integration/tickets [GET]"

    + buy_value (number, optional) - Valor da compra no estabelecimento.
    
    + cod_desc (string, optional) -  Campo livre para o estabelecimento informar qualquer informação adicional da captura.

    + alt_birthday (string, optional) - Data de nascimento do cliente que está sendo capturado no padrão YYYY-MM-DD.
    
        Essa informação será mostrada na página do cliente, porém não sobrepondo a informação do cliente original caso
        o mesmo tenha fornecido alguma após baixar o aplicativo.

    + gender (string, optional) - Sexo do cliente que está sendo capturado.
    
        Valores disponíveis: [MALE, FEMALE, OTHER]
        
        Essa informação será mostrada na página do cliente, porém não sobrepondo a informação do cliente original caso
        o mesmo tenha fornecido alguma após baixar o aplicativo.

    + nickname (string, optional) - Nome do cliente que está sendo capturado.
    
        Essa informação será mostrada na página do cliente, porém não sobrepondo a informação do cliente original caso
        o mesmo tenha fornecido alguma após baixar o aplicativo.

    + custom_segmentations (array, optional) - Array de identificadores de segmentação personalizada.
    
        Pode ser obtido através do endpoint "/integration/getCustomSegmentations [GET]"

+ request

    + Headers
    
            Token: <Token Privado StayApp>
            Content-type: application/x-www-form-urlencoded
    
    + Body
    
            {
                "number": "5562999999999",
                "amount": 10,
                "ticket_id": "-LFKA45HI3I3H5511",
                "buy_value": 49.99,
                "cod_desc": "mesa 22",
                "alt_birthday": "1990-03-13",
                "gender": "FEMALE",
                "nickname": "Jeniffer",
                "custom_segmentations": [
                    "-LXKYWPry1SUp7om20ts"
                ]
            }
          

+ Response 200 (application/json)

    Captura realizada com sucesso! Caso os dados opcionais alt_birthday,
    gender ou nickname sejam registrados incorretamente será mostrado seus respectivos erros, porém
    a captura prosseguirá sem inserção desses atributos opcionais:
    
    + Body

            {
                "stamp_id": "-LWkHkx6bZDvA1Z_59jy"
            }
            

+ Response 400 (application/json)

    Dados obrigatórios invalidos, ou Token de integração invalido, ou não informado no header:
    
    + Body

            {
                "error": "token-not-found/token-invalid/invalid-parameters"
            }
  
## Segmentações personalizadas [/integration/getCustomSegmentations{?is_canceled}]

Endpoint para consulta de segmentações personalizadas

+ Parameters

    + is_canceled: false (boolean, optional) - Filtrar pelo status da segmentação personalizada.
        + Default: `false`
          
### Consulta de segmentações personalizadas [GET]

+ request

    + Headers
    
            Token: <Token Privado StayApp>
            Content-type: application/x-www-form-urlencoded
            
+ Response 200 (application/json)
    
    + Body

            [
                {
                    "id": "-LXKYWPry1SUp7om20ts",
                    "name": "Comprou Sorvete",
                    "is_canceled": false
                },
                {
                    "id": "-LXKuvQjj7Cq_kFysUzF",
                    "name": "Campanha 2019",
                    "is_canceled": false
                },
                {
                    "id": "-LXsfZGeMYtrgo1ATTan",
                    "name": "Comprou via Delivery",
                    "is_canceled": true
                }
            ]